[build]
  base = "."
  command = "npm run build --prefix web"
  publish = "web/dist"
  functions = "web/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@consumet/extensions", "got-scraping", "got"]

[functions."anineko-health-check"]
  schedule = "0 */6 * * *"



